-- Migration number: 0013 	 2026-02-26T21:00:00.000Z
CREATE TABLE venues (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tournament_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  courts_count INTEGER DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE events ADD COLUMN venue_id INTEGER;
ALTER TABLE matches ADD COLUMN venue_id INTEGER;
